import { normalizeSpeciality } from "@/lib/utils";

export const LICENCE_SPECIALITIES = [
    "COMMUNICATION DIGITALE & WEBMARKETING (CDM)",
    "COMMERCE INTERNATIONAL ET E-BUSINESS (CIB)",
    "RÉSEAUX INFORMATIQUES, MOBILITÉ ET SÉCURITÉ (RMS)",
    "RÉSEAUX ET GÉNIE LOGICIEL (RGL)",
    "ENTREPRENEURIAT ET GESTION DE PROJETS (EGP)",
    "DROIT DES AFFAIRES ET CARRIÈRES JUDICIAIRES (DCJ)",
    "GESTION DES TRANSPORTS ET LOGISTIQUE (GTL)",
    "AUDIT ET CONTRÔLE DE GESTION (CG)",
    "BANQUE ET FINANCE D’ENTREPRISE (BF)",
    "MARKETING COMMUNICATION ET MULTIMÉDIA (MCM)",
    "MANAGEMENT DES RESSOURCES HUMAINES (MRH)",
    "AGRONOMIE (AGR)",
    "ELECTRONIQUE ET ELECTROTECHNIQUE (ELT)",
    "GENIE CIVIL (GEC)",
    "DATA SCIENCES (DS)",
    "INTELLIGENCE ARTIFICIELLE ET OBJETS CONNECTES (IAOC)"
].map(normalizeSpeciality);

export const MASTER_SPECIALITIES = [
    "AUDIT ET CONTRÔLE DE GESTION ( MAACO )",
    "COMMUNICATION ET MARKETING ( MACMA )",
    "EXPERTISE COMMERCIALE ET BUSINESS DEVELOPMENT ( MECOB)",
    "TRANSPORT & SUPPLY CHAIN ( MATRAS)",
    "FINANCE ( MAFINE)",
    "GÉNIE INFORMATIQUE ET RÉSEAUX ( MAGIRE)",
    "INTELLIGENCE ARTIFICIELLE ET BIG DATA ( MIAD)",
    "SÉCURITÉ DES SYSTÈMES INFORMATIQUES ( MASSI)",
    "MANAGEMENT DES ENTREPRISES ( MAMES )",
    "FISCALITÉ ET DROIT DES AFFAIRES ( MAFIDA )",
    "MANAGEMENT DE LA QUALITÉ ET DES PROJETS ( MAQUAP )",
    "MANAGEMENT DES RESSOURCES HUMAINES ( MAMREH )",
    "DEVELOPPEMENT DES COLLECTIVITES LOCALES ET MARCHES PUBLICS( MADEC )",
    "INGENIERIE JURIDIQUE ET CARRIERES JUDICIAIRES ( MICAJ )",
    "MARKETING DIGITAL ET STRATEGIE MULTIMEDIA ( MADIM )",
    "DATA SCIENCES ( MADAS )"
].map(normalizeSpeciality);
